# ===================================================================
# Dynamic Project Configuration File (config.yaml)
# ===================================================================
# This file is the single source of truth for the entire Smart Hub system.
# The bridge script will dynamically build its logic based on this file.
#
# direction: TO_CLOUD (for sensors), FROM_CLOUD (for actuators), BIDIRECTIONAL (for both)
# type: The data type expected (String, Float, Integer, Boolean, Dimmed, Color)
# ===================================================================

# --- Arduino Cloud Credentials (Account A: Environment) ---
account_a:
  # Variables for this account:
  # - Lights
  # - Curtain
  # - Thermostat
  # - HVAC
  # - Kettle
  enabled: true
  device_id: "a5ae4bba-2de1-4550-a15a-ee4d37d8a75b"
  secret_key: "?bWig6rFqOJquyU@IgClVQeNL"
  variables:
    - name: "lights" # Classroom lighting
      direction: "FROM_CLOUD" # Can be controlled by the cloud
      topic: "classroom/lighting" # Base topic
      type: "Color" # Color custom data type for RGB values

    - name: "curtain"
      direction: "FROM_CLOUD"  # Can be controlled AND report status
      topic: "classroom/curtain"  # Base topic
      type: "Boolean"

    - name: "thermostat"
      direction: "TO_CLOUD"
      topic: "classroom/thermostat"
      key_in_payload: "temp"
      type: "Float"

    - name: "hVAC"
      direction: "BIDIRECTIONAL"  # Can be controlled AND report status
      topic: "classroom/hvac"  # Base topic
      type: "Boolean"

    - name: "kettle"
      direction: "BIDIRECTIONAL"
      topic: "classroom/kettle"
      key_in_payload: "state"
      type: "Boolean"

# --- Arduino Cloud Credentials (Account B: Security) ---
account_b:
  # Variables for this account:
  # - Window
  # - Light
  # - Door
  # - Lock
  # - Motion
  enabled: true
  device_id: "e6a92bb5-fd57-4251-aa15-346a3c988e1e"
  secret_key: "2BVKUhsYLiUBcuynE?1r4lAiM"
  variables:
    - name: "window"
      direction: "TO_CLOUD"
      topic: "classroom/window"
      key_in_payload: "contact"
      type: "Boolean"

    - name: "light"
      direction: "FROM_CLOUD"  # Can be controlled by the cloud
      topic: "classroom/light"
      type: "Dimmed"

    - name: "door"
      direction: "TO_CLOUD"
      topic: "classroom/door"
      key_in_payload: "contact"
      type: "Boolean"

    - name: "lock"
      direction: "BIDIRECTIONAL"
      topic: "classroom/lock"
      key_in_payload: "lock"
      type: "Boolean"

    - name: "motion"
      direction: "TO_CLOUD"
      topic: "classroom/motion"
      key_in_payload: "motion"
      type: "Boolean"