# ===================================================================
# Dynamic Project Configuration File (config.yaml)
# ===================================================================
# This file is the single source of truth for the entire Smart Hub system.
# The bridge script will dynamically build its logic based on this file.
#
# direction: TO_CLOUD (for sensors), FROM_CLOUD (for actuators), BIDIRECTIONAL (for both)
# type: The data type expected (String, Float, Integer, Boolean, Dimmed, Color)
# ===================================================================

# --- Local MQTT Broker Configuration ---
local_mqtt_broker:
  host: "localhost" # HUB Router IP Address Or "localhost" if running on the same machine
  port: 1883 # Default MQTT port

# --- Arduino Cloud Credentials (Account A: Environment) ---
account_a:
  enabled: true
  device_id: "a5ae4bba-2de1-4550-a15a-ee4d37d8a75b"
  secret_key: "?bWig6rFqOJquyU@IgClVQeNL"
  variables:
    - name: "lights"
      direction: "BIDIRECTIONAL"
      topic: "classroom/lights"
      type: "Color"

    - name: "curtain"
      direction: "BIDIRECTIONAL"
      topic: "classroom/curtain"
      type: "Boolean"

    - name: "thermostat"
      direction: "TO_CLOUD"
      topic: "classroom/thermostat"
      type: "Float"

    - name: "hVAC"
      direction: "BIDIRECTIONAL"
      topic: "classroom/hvac"
      type: "Boolean"

    - name: "kettle"
      direction: "BIDIRECTIONAL"
      topic: "classroom/kettle"
      type: "Boolean"

# --- Arduino Cloud Credentials (Account B: Security) ---
account_b:
  enabled: true
  device_id: "e6a92bb5-fd57-4251-aa15-346a3c988e1e"
  secret_key: "2BVKUhsYLiUBcuynE?1r4lAiM"
  variables:
    - name: "window"
      direction: "TO_CLOUD"
      topic: "classroom/window"
      type: "Boolean"

    - name: "light"
      direction: "FROM_CLOUD"
      topic: "classroom/light"
      type: "Dimmed"

    - name: "door"
      direction: "TO_CLOUD"
      topic: "entrance/door"
      type: "Boolean"

    - name: "lock"
      direction: "BIDIRECTIONAL"
      topic: "entrance/lock"
      type: "Boolean"

    - name: "motion"
      direction: "TO_CLOUD"
      topic: "classroom/motion"
      type: "Boolean"
