# ===================================================================
# Dynamic Project Configuration File (config.yaml) - v2.5.1
# ===================================================================
# This file is the single source of truth for the hub system.
# The bridge script dynamically builds its logic based on this file.
#
# direction: TO_CLOUD (sensors), FROM_CLOUD (actuators), BIDIRECTIONAL
# type: String, Float, Integer, Boolean, Dimmed, Color
# ===================================================================

# --- Local MQTT Broker Configuration ---
local_mqtt_broker:
  host: "localhost" # IP Address of the machine running the hub, or "localhost"
  port: 1883        # Default MQTT port

# --- Arduino Cloud Account A: Environment ---
account_a:
  enabled: true
  device_id: "a5ae4bba-2de1-4550-a15a-ee4d37d8a75b"
  secret_key: "?bWig6rFqOJquyU@IgClVQeNL"
  variables:
    - name: "lights"
      direction: "BIDIRECTIONAL"
      topic: "classroom/lights"
      type: "Color"

    - name: "curtain"
      direction: "BIDIRECTIONAL"
      topic: "classroom/curtain"
      type: "Boolean"

    - name: "thermostat"
      direction: "TO_CLOUD"
      topic: "classroom/thermostat"
      type: "Float"

    - name: "hVAC"
      direction: "BIDIRECTIONAL"
      topic: "classroom/hvac"
      type: "Boolean"

    - name: "kettle"
      direction: "BIDIRECTIONAL"
      topic: "classroom/kettle"
      type: "Boolean"

# --- Arduino Cloud Account B: Security ---
account_b:
  enabled: true
  device_id: "e6a92bb5-fd57-4251-aa15-346a3c988e1e"
  secret_key: "2BVKUhsYLiUBcuynE?1r4lAiM"
  variables:
    - name: "window"
      direction: "TO_CLOUD"
      topic: "classroom/window"
      type: "Boolean"

    - name: "light"
      direction: "BIDIRECTIONAL"
      topic: "classroom/light"
      type: "Dimmed"

    - name: "door"
      direction: "TO_CLOUD"
      topic: "entrance/door"
      type: "Boolean"

    - name: "lock"
      direction: "BIDIRECTIONAL"
      topic: "entrance/lock"
      type: "Boolean"

    - name: "motion"
      direction: "TO_CLOUD"
      topic: "classroom/motion"
      type: "Boolean"
